export interface IInterviewData {
  [key: string]: {
    [subKey: string]: string[] | { [subSubKey: string]: string[] };
  };
}

export const interviewPrepration: IInterviewData = {
  backend: {
    springBoot: [
      'How does @SpringBootApplication work internally?',
      'What happens during application startup lifecycle?',
      'Difference between @ComponentScan and @EnableAutoConfiguration?',
      'How does BeanFactory differ from ApplicationContext?',
      'What is circular dependency and how to resolve it?',
      'How does Spring manage thread safety for singleton beans?',
      'What is proxy in Spring AOP?',
      'JDK Dynamic Proxy vs CGLIB?',
      'How does @Transactional work internally?',
      'What is transaction propagation and isolation?',
      'How to handle distributed transactions?',
      'What is saga pattern?',
      'Explain Bean Lifecycle in Spring.',
      'Singleton vs Prototype bean scope.',
      'What happens during self-invocation of @Transactional methods?',
      'How do you handle global exceptions using @ControllerAdvice?',
      'What is Dependency Injection?',
      'Why is Constructor Injection preferred over Field Injection?',
    ],
    coreJava: [
      'How do HashMap and ConcurrentHashMap work internally?',
      'How does ConcurrentHashMap achieve thread safety without locking the entire map?',
      'What is the difference between submit() and execute() in ExecutorService?',
      'How do you retrieve a value using Future or CompletableFuture?',
      'Explain Heap vs Stack memory in JVM.',
      'How does Garbage Collection identify memory leaks?',
      'Fail-fast vs Fail-safe iterators?',
      'CompletableFuture vs Future?',
      'How do you chain multiple asynchronous API calls using CompletableFuture?',
      'Explain Java 8 Stream API lifecycle.',
      'Intermediate vs Terminal operations in Stream API?',
      'What is the purpose of volatile keyword?',
      'How does volatile guarantee visibility but not atomicity?',
      'Can you force Garbage Collection programmatically?',
      'What happens internally when System.gc() is called?',
    ],

    jpaHibernate: [
      'How does Hibernate first-level and second-level cache work?',
      'What is dirty checking in JPA?',
      'What is N+1 problem and how to fix it?',
      'How does pagination work at DB level?',
      'What is optimistic vs pessimistic locking?',
    ],

    microServices: [
      'What are microservices?',
      'Monolith vs Microservices?',
      'What are the advantages of microservices?',
      'What are the disadvantages of microservices?',
      'What is centralized logging?',
      'What is retry mechanism?',
      'What is the role of Spring Cloud in microservices?',
      'What is OpenFeign?',
      'OpenFeign vs RestTemplate?',
      'Zuul vs Spring Cloud Gateway?',
      'What is Spring Cloud Config Server?',
      'Inter-service communication: Synchronous vs Asynchronous?',
      'What is Event-Driven Architecture (EDA)?',
      'What is Outbox Pattern?',
      'What is Event Sourcing?',
      'URI Versioning vs Header Versioning?',
      'What is rate limiting?',
      'What is OAuth2 vs OIDC?',
      'Readiness Probe vs Liveness Probe?',
      'Docker vs Kubernetes?',
      'How would you design an end-to-end scalable microservices architecture?',
      'How do you design high availability systems?',
      'What is load balancing at application level?',
      'How does API Gateway work?',
      'What is eventual consistency?',
      'What is CAP theorem?',
      'How does circuit breaker work internally?',
      'What is bulkhead pattern?',
      'Choreography vs Orchestration in Saga Pattern?',
      'How do you handle cascading failures across microservices?',
      'Explain Circuit Breaker states (Closed, Open, Half-Open).',
      'What is Service Discovery?',
      'How does Netflix Eureka work internally?',
      'How do microservices register and discover each other?',
      'How do you secure a microservices ecosystem?',
      'How does JWT propagation work across microservices?',
      'What is CQRS pattern?',
      'Why is CQRS beneficial for high-read systems?',
      'Failures and Fault Tolerance in Microservices',
      'JWT vs OAuth2 vs OIDC',
      'Bulkhead Pattern and Rate Limiting',
      'API Versioning strategies',
      'How to maintain Data Consistency across Microservices?',
      'What is Idempotency?',
      'Explain Saga Pattern in Microservices',
      'What is Event Driven Architecture?',
      'Synchronous vs Asynchronous Communication in Microservices',
      'What is Spring Cloud Config Server?',
      'Zuul vs Spring Cloud Gateway',
      'What is OpenFeign?',
      'What is Netflix Eureka?',
      'What is Distributed Tracing?',
      'Explain Retry Mechanism in Microservices',
      'Explain Circuit Breaker Pattern',
      'Centralized Logging in Microservices',
      'Load Balancing in Microservices',
      'What is Service Discovery in Microservices?',
      'What is API Gateway?',
      'Design scalable end-to-end microservices architecture',
      'Docker vs Kubernetes',
    ],

    security: [
      'How does OAuth2 flow work internally?',
      'What is JWT token lifecycle?',
      'How to prevent SQL Injection and XSS?',
      'What is CORS and how browser enforces it?',
      'How does Spring Security filter chain work?',
    ],

    restApi: ['What is idempotency in REST?', 'How to design versioned APIs?'],

    kafka: [
      'How does Kafka ensure message durability?',
      'What is consumer group?',
      'What is exactly-once processing?',
    ],

    reactive: [
      'How does WebClient differ from RestTemplate?',
      'What is backpressure in reactive streams?',
      'Mono vs Flux use cases?',
      'How does non-blocking IO improve scalability?',
    ],

    kubernetes: [
      'How does Kubernetes manage pod scaling?',
      'What is HPA?',
      'What is service mesh?',
    ],

    caching: ['How does Redis caching strategy work?', 'Cache eviction policies?', 'What is TTL?'],

    database: [
      'How do you optimize a slow SQL query?',
      'How does database indexing work internally?',
      'When can a database index be ignored by the query planner?',
      'What is Cache Avalanche?',
      'What is Cache Stampede?',
      'How do you handle Cache Avalanche and Cache Stampede?',
    ],

    production: [
      'How do you debug memory leaks?',
      'How to analyze heap dump?',
      'How to trace slow APIs in production?',
      'What is distributed tracing?',
      'What is blue-green vs canary deployment?',
      'How do you handle zero-downtime deployments?',
    ],
    systemDesign: [
      'Design a Flight Search Cache using Redis.',
      'How do you handle delayed third-party API responses asynchronously?',
      'How do you implement distributed logging using Correlation IDs?',
      'Design a Flight Booking Engine.',
      'What is Database Sharding?',
      'How do you horizontally shard large databases?',
      'How do you choose a shard key?',
    ],
    coding: {
      DSA: [
        'Detect a loop in Linked List using Floyd Cycle Detection.',
        'Implement Merge Sort.',
        'Find intersection point of two Linked Lists.',
        'Count subarrays whose sum equals K.',
        'Sort array of 0s, 1s and 2s using Dutch National Flag Algorithm.',
        'Find spikes in stock price array',
        'Find all combinations of a string',
        'Find missing number in an array',
        'Check valid parentheses',
        'Product of array except self',
        'Find common elements from three ArrayLists',
      ],
      java8Streams: [
        'Find duplicates in an array using Stream API.',
        'Sort employee list in ascending and descending order using Streams.',
        'Find highest salary employee from a department using Streams.',
        'Find average of even numbers using Streams.',
        'How to use sorting in Java 8 Streams?',
        'Find employee count in each department using Streams.',
        'Find employees by location and sort alphabetically using Streams.',
        'Find occurrence and frequency of employee names.',
        'Print only numbers from an alphanumeric array using Streams.',
        'Find sum of entire array using Streams.',
        'Find even numbers and multiply them by 2 using Streams.',
        'Find occurrence of each word in a string.',
        'Find common elements from three ArrayLists.',
        'Count every character in a string using Streams.',
        'Find second highest salary using Streams.',
        'Difference between map(), flatMap(), and filter().',
        'Handle null values safely in Streams.',
        'Partition numbers into even and odd using Streams.',
        'Find longest string in a list using Streams.',
        'Convert List to Map using Streams and handle duplicate keys.',
        'Find top 3 highest paid employees.',
        'Parallel Stream vs Stream.',
        'Remove duplicates while preserving insertion order using Streams.',
        'Find longest string in a list using Java Streams',
        'Remove duplicate elements while preserving order using Java Streams',
        'Find top 3 highest paid employees using Java Streams',
        'Partition even and odd numbers using Java Streams',
        'Convert List to Map using Java Streams',
        'How to handle null values safely in Java Streams?',
        'Parallel Streams vs Streams in Java',
        'Difference between map(), flatMap(), and filter() in Java Streams',
      ],
      coreJavaCoding: [
        'Convert String to Integer without using API.',
        'Find first occurrence of a character in a string.',
        'Find all possible combinations of a string.',
        'Check for valid parentheses.',
        'Find minimum occurring character in a string.',
        'Product of array except self.',
        'Check if a string has all unique characters.',
        'Find spikes in a stock price array.',
      ],
    },
  },
  frontend: {
    angular: [
      'What is Angular and its core features?',
      'Explain Angular architecture.',
      'What are components in Angular?',
      'What is a module (NgModule)?',
      'What are standalone components?',

      'What are directives?',
      'Types of directives?',
      'Difference between component and directive.',

      'Explain data binding and its types.',
      'What is interpolation?',
      'Property binding vs Event binding?',
      'What is two-way data binding?',

      'What is Dependency Injection?',
      'What are services in Angular?',
      'How do you create and use services?',

      'How do components communicate?',
      'Parent to child communication?',
      'Child to parent communication?',
      'Communication between unrelated components?',

      'What is routing in Angular?',
      'What is router-outlet?',
      'What is lazy loading?',
      'What are route guards?',

      'Difference between template-driven and reactive forms?',
      'How to validate forms?',
      'Custom validators in Angular?',

      'What are pipes?',
      'Difference between pure and impure pipes?',

      'What is Change Detection?',
      'What is OnPush Change Detection?',
      'What is trackBy in *ngFor?',

      'What is RxJS?',
      'Difference between Observable and Promise?',
      'What is Subject in RxJS?',
      'BehaviorSubject vs Subject?',
      'ReplaySubject vs BehaviorSubject?',

      'How to make HTTP calls in Angular?',
      'How do you handle API errors?',
      'What is HttpInterceptor?',
      'How do you secure routes?',

      'How do you optimize Angular application performance?',
      'What is Ahead-of-Time (AOT) compilation?',
      'What is Just-in-Time (JIT) compilation?',

      'What are Angular lifecycle hooks?',
      'Explain ngOnInit and ngOnDestroy.',
      'What is ViewChild?',
      'What is ContentChild?',

      'What are Angular Signals?',
      'How to handle multiple API calls sequentially?',
      'How to split large components?',
      'Best practices for scalable Angular applications?',
    ],

    angularAdvanced: [
      'Zone.js and change detection internals',
      'Custom structural directives',
      'Content projection (ng-content)',
      'Dynamic component loading',
      'Module Federation',
      'Standalone APIs migration',
      'Signals vs RxJS',
      'SSR vs CSR',
      'Angular hydration',
      'State management (NgRx/Signals Store)',
      'Memory leak debugging',
      'TrackBy and rendering optimization',
      'Angular Elements',
      'Custom form controls (ControlValueAccessor)',
      'Route resolvers and preloading strategies',
    ],

    javascript: [
      'What is JavaScript?',
      'Primitive vs Non-Primitive data types',
      'Pass by Value vs Pass by Reference',
      'Truthy and Falsy values',
      'Difference between == and ===',
      'Type Coercion',
      'Nullish Coalescing Operator',
      'Optional Chaining',
      'Spread and Rest Operators',
      'Destructuring in JavaScript',
      'Scope: Global, Function, and Block Scope',
      'Lexical Environment',
      'this keyword in JavaScript',
      'call(), apply(), and bind()',
      'Higher-Order Functions',
      'Callback Functions',
      'Pure Functions',
      'Currying in JavaScript',
      'Object.create()',
      'Prototype Chain',
      'Constructor Functions',
      'Classes in JavaScript',
      'Inheritance in JavaScript',
      'new Keyword',
      'Event Loop',
      'Call Stack',
      'Web APIs',
      'Callback Queue',
      'Microtask Queue',
      'Promises',
      'Promise Chaining',
      'Promise.all(), Promise.race(), Promise.allSettled(), Promise.any()',
      'async and await',
      'Fetch API Basics',
      'Error Handling with try/catch',
      'Arrow Functions',
      'Function Declaration vs Function Expression',
      'Debouncing',
      'Throttling',
      'Event Bubbling',
      'Event Capturing',
      'Event Delegation',
      'preventDefault()',
      'stopPropagation()',
      'Custom Events',
      'DOM Selection and Manipulation',
    ],

    react: [
      'What is React?',
      'JSX in React',
      'React Components',
      'Props in React',
      'State in React',
      'Controlled vs Uncontrolled Components',
      'Keys in React',
      'useState Hook',
      'useEffect Hook',
      'useRef Hook',
      'useMemo vs useCallback',
      'useReducer Hook',
      'useContext Hook',
      'Context API',
      'Reconciliation in React',
      'React Rendering Lifecycle',
      'React.memo',
      'Custom Hooks',
      'Lazy Loading and Code Splitting',
      'Redux vs Zustand vs React Query vs Context',
      'Error Boundaries',
      'React Portals',
      'Suspense Basics',
      'Virtual DOM',
    ],
    coding: {
      machineCoding: [
        'Build Counter Component',
        'Build Todo App',
        'Build Modal Component',
        'Build Tabs Component',
        'Build Accordion Component',
        'Build Autocomplete Typeahead Search',
        'Build Pagination',
        'Build Infinite Scroll',
        'Build Sortable Table',
        'Build Filterable Product List',
        'Build File Explorer',
        'Build Nested Comments',
        'Build Virtualized List',
        'Build Config-Driven Form Builder',
      ],

      javascriptCoding: [
        'Implement Array.prototype.map',
        'Implement Array.prototype.filter',
        'Implement Array.prototype.reduce',
        'Implement Promise.all',
        'Implement debounce',
        'Implement throttle',
        'Implement flattenArray',
        'Implement deepClone',
        'Implement groupBy',
        'Implement memoize',
        'Implement once Function',
        'Build a Simple Event Emitter',
      ],
    },
  },
};

/**
 * Converts camelCase or snake_case key to readable display name
 * Examples:
 * 'springBoot' -> 'Spring Boot'
 * 'jpaHibernate' -> 'Jpa Hibernate'
 * 'java8Streams' -> 'Java8 Streams'
 * 'coreJava' -> 'Core Java'
 */
export function convertKeyToDisplayName(key: string): string {
  return (
    key
      // Insert space before uppercase letters (camelCase)
      .replace(/([a-z])([A-Z])/g, '$1 $2')
      // Insert space before numbers
      .replace(/([a-zA-Z])(\d)/g, '$1 $2')
      // Replace underscores with spaces (snake_case)
      .replace(/_/g, ' ')
      // Capitalize first letter of each word
      .split(' ')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join(' ')
  );
}

